spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        ## service1
        - id: lvservice
          uri: lb://lvservice
          predicates:
            - Path=/lvservice/**
          filters:
            - StripPrefix=1
        ## service2
        - id: RegisterService
          uri: lb://RegisterService
          predicates:
            - Path=/RegisterService/**
          filters:
            - StripPrefix=1
        ## service3
        - id: lps
          uri: lb://lps
          predicates:
            - Path=/lps/**
          filters:
            - StripPrefix=1
       
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

      


  
