spring: 
  application:
    name: apigateway_server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
#        # service1
#        - id: lvservice
#          uri: lb://lvservice
#          predicates:
#            - Path=/lvservice/**
#          filters:
#            - StripPrefix=1
        # service2apigateway_server
        - id: register-service
          uri: lb://register-service
          predicates:
            - Path=/register-service/**
          filters:
            - StripPrefix=1
  main:    allow-bean-definition-overriding: true
    web-application-type: reactive    
       
server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://eureka-naming-server.capeelectric.internal:8761
#  instance:
#    preferIpAddress: true
#    instance:
#      ip-address: true
     
  
      


  
