spring: 
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        ## service1
#        - id: lvservice
#          uri: lb://lvservice
#          predicates:
#            - Path=/lvservice/**
#          filters:
#            - StripPrefix=1
        ## service2
        - id: registerservice
          uri: lb://registerservice
          predicates:
            - Path=/registerservice/**
          filters:
            - StripPrefix=1
        ## service3
#        - id: lpsservice
#          uri: lb://lpsservice
#          predicates:
#            - Path=/lpsservice/**
#          filters:
#            - StripPrefix=1
  main:    allow-bean-definition-overriding: true
    web-application-type: reactive    
       
server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://Netflixeurekanamingserver-env.eba-wzmkebma.ap-south-1.elasticbeanstalk.com/eureka

  
      


  
