spring:
  application:
    name: api-gateway

  ##GATEWAY CONFIGURATIONS

  cloud:
    gateway:
      routes:
        ## service1
        - id: lvservice
          uri: lb://lvservice
          predicates:
            - Path=/lvservice/**
          filters:
            - StripPrefix=1

        ## Service2
        - id: lpsservice
          uri: lb://lpsservice
          predicates:
            - Path=/lpsservice/**
          filters:
            - StripPrefix=1
server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


  
